# Generated by Django 5.2 on 2025-04-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navmain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="incident_type",
            field=models.CharField(
                choices=[
                    ("fire", "Fire"),
                    ("ems", "EMS"),
                    ("traffic", "Traffic"),
                    ("crime", "Crime"),
                    ("natural", "Natural"),
                ],
                max_length=10,
            ),
        ),
    ]
